# Generated by Django 4.1.4 on 2023-01-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=120)),
                ('manzili', models.CharField(max_length=120)),
                ('narx', models.CharField(max_length=120)),
            ],
        ),
        migrations.RenameModel(
            old_name='Zapravka',
            new_name='Benzin',
        ),
        migrations.RenameField(
            model_name='benzin',
            old_name='turi',
            new_name='narx',
        ),
    ]
